create table user_account (
    id bigint generated by default as identity primary key,
    full_name varchar(160) not null,
    email varchar(254) not null unique,
    password_hash varchar(100) not null,
    role varchar(30) not null,
    registered_at timestamp with time zone not null default current_timestamp,
    active boolean not null default true,
    constraint ck_user_role check (role in ('DIRECTOR', 'COORDINATOR', 'SCOUT'))
);

create table player (
    id bigint generated by default as identity primary key,
    external_id varchar(120) unique,
    full_name varchar(160) not null,
    birth_date date not null,
    nationality varchar(100),
    club varchar(160),
    league varchar(160),
    preferred_foot varchar(20),
    primary_position varchar(40) not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uq_player_identity unique (full_name, birth_date),
    constraint ck_preferred_foot check (
        preferred_foot is null or preferred_foot in ('LEFT', 'RIGHT', 'BOTH')
    )
);

create table player_secondary_position (
    player_id bigint not null references player(id) on delete cascade,
    position varchar(40) not null,
    primary key (player_id, position)
);

create table attribute_catalog (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    display_name varchar(100) not null,
    category varchar(40) not null,
    description varchar(500) not null,
    active boolean not null default true
);

create table evaluation (
    id bigint generated by default as identity primary key,
    player_id bigint not null references player(id),
    scout_id bigint not null references user_account(id),
    observation_date date not null,
    opponent varchar(160),
    competition varchar(160),
    observed_position varchar(40) not null,
    strengths varchar(2000),
    weaknesses varchar(2000),
    general_comment varchar(4000),
    status varchar(20) not null,
    version_number integer not null default 1,
    previous_evaluation_id bigint references evaluation(id),
    created_at timestamp with time zone not null default current_timestamp,
    confirmed_at timestamp with time zone,
    constraint ck_evaluation_status check (status in ('DRAFT', 'CONFIRMED')),
    constraint ck_evaluation_version check (version_number >= 1),
    constraint ck_evaluation_confirmation check (
        (status = 'DRAFT' and confirmed_at is null)
        or (status = 'CONFIRMED' and confirmed_at is not null)
    )
);

create table evaluation_score (
    evaluation_id bigint not null references evaluation(id) on delete cascade,
    attribute_id bigint not null references attribute_catalog(id),
    score_value integer not null,
    primary key (evaluation_id, attribute_id),
    constraint ck_evaluation_score check (score_value between 1 and 10)
);

create table sporting_need (
    id bigint generated by default as identity primary key,
    title varchar(180) not null,
    description varchar(2000),
    status varchar(20) not null default 'ACTIVE',
    created_by bigint not null references user_account(id),
    created_at timestamp with time zone not null default current_timestamp,
    closed_at timestamp with time zone,
    constraint ck_need_status check (status in ('ACTIVE', 'CLOSED'))
);

create table need_version (
    id bigint generated by default as identity primary key,
    need_id bigint not null references sporting_need(id),
    version_number integer not null,
    requested_position varchar(40) not null,
    league varchar(160),
    minimum_age integer,
    maximum_age integer,
    nationality varchar(100),
    preferred_foot varchar(20),
    created_by bigint not null references user_account(id),
    created_at timestamp with time zone not null default current_timestamp,
    constraint uq_need_version unique (need_id, version_number),
    constraint ck_need_age_range check (
        (minimum_age is null or minimum_age >= 15)
        and (maximum_age is null or maximum_age <= 60)
        and (minimum_age is null or maximum_age is null or minimum_age <= maximum_age)
    )
);

create table search_criterion (
    id bigint generated by default as identity primary key,
    need_version_id bigint not null references need_version(id) on delete cascade,
    attribute_id bigint not null references attribute_catalog(id),
    target_value integer not null,
    weight integer not null,
    exclusion_minimum integer,
    constraint uq_version_attribute unique (need_version_id, attribute_id),
    constraint ck_target_value check (target_value between 1 and 10),
    constraint ck_criterion_weight check (weight between 1 and 5),
    constraint ck_exclusion_minimum check (
        exclusion_minimum is null or exclusion_minimum between 1 and 10
    )
);

create table search_execution (
    id bigint generated by default as identity primary key,
    need_version_id bigint not null references need_version(id),
    executed_by bigint not null references user_account(id),
    executed_at timestamp with time zone not null default current_timestamp,
    analyzed_player_count integer not null default 0,
    result_count integer not null default 0,
    constraint ck_execution_counts check (
        analyzed_player_count >= 0 and result_count >= 0
    )
);

create table search_result (
    id bigint generated by default as identity primary key,
    execution_id bigint not null references search_execution(id) on delete cascade,
    player_id bigint not null references player(id),
    compatibility_percentage numeric(5,2),
    calculation_status varchar(30) not null,
    position_match_type varchar(20) not null,
    scout_count integer not null default 0,
    evaluation_count integer not null default 0,
    last_evaluation_date date,
    uses_alternative_position boolean not null default false,
    calculation_detail text,
    constraint uq_execution_player unique (execution_id, player_id),
    constraint ck_compatibility_percentage check (
        compatibility_percentage is null
        or compatibility_percentage between 0 and 100
    ),
    constraint ck_calculation_status check (
        calculation_status in (
            'CALCULATED', 'PRELIMINARY', 'INSUFFICIENT_DATA', 'PENDING_EVALUATION'
        )
    ),
    constraint ck_position_match check (position_match_type in ('PRIMARY', 'SECONDARY')),
    constraint ck_result_counts check (scout_count >= 0 and evaluation_count >= 0)
);

create table candidate (
    id bigint generated by default as identity primary key,
    player_id bigint not null references player(id),
    need_version_id bigint not null references need_version(id),
    source_result_id bigint not null references search_result(id),
    current_status varchar(30) not null default 'DETECTED',
    selected_at timestamp with time zone not null default current_timestamp,
    selected_by bigint not null references user_account(id),
    constraint uq_candidate_version unique (player_id, need_version_id),
    constraint ck_candidate_status check (
        current_status in (
            'DETECTED', 'UNDER_OBSERVATION', 'SHORTLISTED', 'RECOMMENDED', 'DISCARDED'
        )
    )
);

create table candidate_status_change (
    id bigint generated by default as identity primary key,
    candidate_id bigint not null references candidate(id) on delete cascade,
    previous_status varchar(30),
    new_status varchar(30) not null,
    reason varchar(1000),
    changed_by bigint not null references user_account(id),
    changed_at timestamp with time zone not null default current_timestamp,
    constraint ck_discard_reason check (new_status <> 'DISCARDED' or reason is not null)
);

create table csv_import (
    id bigint generated by default as identity primary key,
    file_name varchar(255) not null,
    imported_by bigint not null references user_account(id),
    imported_at timestamp with time zone not null default current_timestamp,
    row_count integer not null,
    imported_count integer not null,
    rejected_count integer not null,
    status varchar(20) not null,
    constraint ck_import_counts check (
        row_count >= 0 and imported_count >= 0 and rejected_count >= 0
    ),
    constraint ck_import_status check (status in ('PREVIEW', 'CONFIRMED', 'FAILED'))
);

create table import_error (
    id bigint generated by default as identity primary key,
    import_id bigint not null references csv_import(id) on delete cascade,
    row_number integer not null,
    field_name varchar(100),
    message varchar(1000) not null,
    constraint ck_import_error_row check (row_number >= 1)
);

create index idx_player_league_position on player (league, primary_position);
create index idx_evaluation_player_status on evaluation (player_id, status);
create index idx_evaluation_scout on evaluation (scout_id);
create index idx_need_status on sporting_need (status);
create index idx_result_execution_percentage
    on search_result (execution_id, compatibility_percentage);
create index idx_candidate_version_status
    on candidate (need_version_id, current_status);

insert into attribute_catalog (code, display_name, category, description) values
    ('PASSING', 'Pase', 'TECHNICAL', 'Precisión y calidad de distribución'),
    ('CONTROL', 'Control', 'TECHNICAL', 'Recepción y dominio del balón'),
    ('DRIBBLING', 'Conducción', 'TECHNICAL', 'Traslado del balón bajo control'),
    ('FINISHING', 'Definición', 'TECHNICAL', 'Capacidad de finalizar jugadas'),
    ('VISION', 'Visión', 'TACTICAL', 'Lectura de opciones y espacios'),
    ('POSITIONING', 'Posicionamiento', 'TACTICAL', 'Ocupación adecuada de espacios'),
    ('RECOVERY', 'Recuperación', 'DEFENSIVE', 'Capacidad de recuperar la posesión'),
    ('MARKING', 'Marcaje', 'DEFENSIVE', 'Seguimiento y control del rival'),
    ('SPEED', 'Velocidad', 'PHYSICAL', 'Desplazamiento y aceleración'),
    ('STAMINA', 'Resistencia', 'PHYSICAL', 'Capacidad de sostener el esfuerzo'),
    ('STRENGTH', 'Fuerza', 'PHYSICAL', 'Rendimiento en disputas físicas'),
    ('AERIAL_PLAY', 'Juego aéreo', 'MIXED', 'Rendimiento en acciones por elevación');

